name = "%worker_name%"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "%subdomain_name%", custom_domain = true },
  { pattern = "ava.game.naver.com.%subdomain_name%", custom_domain = true },
  { pattern = "mssdk24-normal-useast2a.tiktokv.com.%subdomain_name%", custom_domain = true },
  { pattern = "app.genflix.co.id.%subdomain_name%", custom_domain = true },
  { pattern = "app.gopay.co.id.%subdomain_name%", custom_domain = true },
  { pattern = "blue.blibli.com.%subdomain_name%", custom_domain = true },
  { pattern = "zaintest.vuclip.com.%subdomain_name%", custom_domain = true },
  { pattern = "cache.netflix.com.%subdomain_name%", custom_domain = true },
  { pattern = "graph.instagram.com.%subdomain_name%", custom_domain = true },
  { pattern = "investor.fb.com.%subdomain_name%", custom_domain = true },
  { pattern = "investors.spotify.com.%subdomain_name%", custom_domain = true },
  { pattern = "m.pubgmobile.com.%subdomain_name%", custom_domain = true },
  { pattern = "web.poe.garena.com.%subdomain_name%", custom_domain = true },
  { pattern = "dl.cvs.freefiremobile.com.%subdomain_name%", custom_domain = true },
  { pattern = "support.zoom.us.%subdomain_name%", custom_domain = true },
  { pattern = "img.email1.vidio.com.%subdomain_name%", custom_domain = true },
  { pattern = "quiz.staging.vidio.com.%subdomain_name%", custom_domain = true },
  { pattern = "quiz.int.vidio.com.%subdomain_name%", custom_domain = true },
  { pattern = "blog.webex.com.%subdomain_name%", custom_domain = true },  
]
workers_dev = false
[vars]
UUID = "%uuid%"
proxyip = "%proxyip%"
